; --- Límites de subida ---
upload_max_filesize = 32M
post_max_size = 32M
memory_limit = 256M
max_execution_time = 60

; --- Configuración para ver los errores (CRÍTICO) ---
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On
error_log = /dev/stderr

; --- Optimización ---
file_uploads = On